# Generated by Django 5.0.3 on 2024-04-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_producto_proveedor_alter_producto_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
