# Generated by Django 5.0.3 on 2024-04-06 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
    ]
